import store from "@/store";
import "@/styles/globals.css";
import { ProductSans } from "@/utils/customFonts";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Provider } from "react-redux";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Primsy India</title>
        <meta name="description" content="Generated by Infinity" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/primsy-rectangles.svg" />
      </Head>
      <Provider store={store}>
        <main className={ProductSans.className}>
          <Component {...pageProps} />
        </main>
      </Provider>
    </>
  );
}
